### ISSUE TITLE
Type checks are a little inefficient

### ISSUE THREAD

**Issue by tobyink** [cxw42/Class-Tiny-ConstrainedAccessor#1]
Instead of this:
```
$av->($constraint, $_[0]);
```

You'd get much better performance using:
```
$compiled->($_[0]) or die $constraint->get_message($_[0]);
```

And you can get the `$compiled` coderef like this outside the accessor:
```
my $compiled = $constraint->compiled_check;
```

This API should work with Type::Tiny and MooseX::Types.

**Comment by cxw42** [comment]
@tobyink Thanks for the tip!  I see that `compiled_check` is in the POD for T::T.  However, I can't find it for MooseX::Types, Moose::Util::TypeConstraints, or Moose::Meta::TypeConstraint, and grep::cpan is timing out on me.  

I do see that Moose::Meta::TypeConstraint has a [`_compiled_type_constraint` accessor](https://metacpan.org/release/Moose/source/lib/Moose/Meta/TypeConstraint.pm#L160) that looks like it would fit the bill.  However, I hesitate to rely on that since it's an underscore method.  

Is there an accessor I'm missing?  (I presume there is.)  If not, would this be worth a PR in Moose requesting a documented RO `Moose::Meta::TypeConstraint::compiled_check` accessor?

**Comment by tobyink** [comment]
Darn, you're right. It's private in Moose.

There is `$type->compile_type_constraint` in Moose, which doesn't have a leading underscore, but is undocumented, and only returns the compiled coderef as a fortunate side-effect because the last statement in the sub compiles it.

**Comment by cxw42** [comment]
Thanks for confirming.  For now, I'll split off a `can('compiled_check')` code path.

**Comment by tobyink** [comment]
This is untested, but you could do something like:

```perl
my $compiled;
if ($type->can('compiled_check')) { # Type::Tiny
  $compiled = $type->compiled_check;
}
elsif (my $method = $type->can('inline_check')||$type->can('_inline_check')) { # Specio, Moose
  $compiled = eval { eval sprintf 'sub { my $value = shift; %s }', $type->$method('$value') };
  # above will fail if type cannot be inlined, so next block isn't `elsif`
}
if (!$compiled) {
  if ($type->can('check')) { # Specio, Moose, Mouse
    $compiled = sub { $type->check(@_) };
  }
  elsif (ref($type) eq 'CODE') { # MooX::Types
    $compiled = sub { eval { $type->(@_); 1 } };
  }
  else {
    die "Dunno how to use this type";
  }
}
```

That should support Type::Tiny, Specio, MooseX::Types, MouseX::Types, and MooX::Types.

**Comment by cxw42** [comment]
@tobyink I will shortly be releasing 0.000002 with support for all those, and have added you to the x_contributors list.  Thanks again for the suggestion and the code!
