### ISSUE TITLE
Unify _get_constraint_sub with Types::TypeTiny::to_TypeTiny?

### ISSUE THREAD

**Issue by cxw42** [cxw42/Class-Tiny-ConstrainedAccessor#9]
I just discovered [Types::TypeTiny/to_TypeTiny](https://metacpan.org/pod/Types::TypeTiny#to_TypeTiny($constraint)), which might be able to replace  [`_get_constraint_sub`](https://github.com/cxw42/Class-Tiny-ConstrainedAccessor/blob/34b2d1b2f01259675b526d0135a4d96f55abe05a/lib/Class/Tiny/ConstrainedAccessor.pm#L172-L242).

@tobyink `_get_constraint_sub` in this module does approximately the same as to_TypeTiny, but also supports Specio and `[\&check, \&get_message]`.  Would you be open to a contribution to Types::TypeTiny to add those two if I can pass the tests in this module otherwise using to_TypeTiny?

**Comment by tobyink** [comment]
to_TypeTiny already supports Specio because it supports any blessed objects that provide `check` and `get_message` methods.

I'd accept one to support `[\&check, \&get_message]` but I'm not sure how long it will be before my next stable release, so you might be better off writing a small helper class like this:

```
package Class::Tiny::ConstraintedAccessor::_Type;
sub check {
  my ($self, $value) = @_;
  $self->[0]->($value);
}
sub get_message {
  my ($self, $value) = @_;
  $self->[1]->($value);
}
```

Then if you have `[\&check, \&get_message]` you can just bless it into that class and to_TypeTiny will then support it. Does that make sense?

**Comment by cxw42** [comment]
@tobyink Thanks for the code and suggestion!  I took the liberty of dropping your code into ef3e64b7238ceaad56b39f6cadb0e054a06e56a9, then rolled a TRIAL release.  I also opened https://rt.cpan.org/Ticket/Display.html?id=131011 along the way.
